### ISSUE TITLE
Docker rtorrent-rutorrent filebot

### ISSUE THREAD

**Issue by THEDARKK** [xataz/dockerfiles#10]
Bonjour , j'ai un petit souci , quand sa build avec filebot.
Sa m'affiche cette erreur  
"Connecting to downloads.sourceforge.net (216.34.181.59:80)
Connecting to vorboss.dl.sourceforge.net (5.10.152.194:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer "

Merci Cordialement

**Comment by xataz** [comment]
Salut,

J'ai lancé un build ce matin, sans aucun soucis.
As-tu mis à jour l'image xataz/alpine:3.4 ?

XataZ

**Comment by AlcyonSuisse** [comment]
J'ai eu la même erreur, mais en insistant c'est passé...
Par contre est ce normale qu'il n'y ai aucun port d'écoute exposé?

**Comment by Djamy** [comment]
J'ai eu la même erreur. Il a fallu que j'ajoute ca-certificates openssl pour que ça passe..

**Comment by xataz** [comment]
Pouvez vous tout les deux refaire un essai.
Normalement là, tout devrait être ok.

**Comment by xataz** [comment]
Je clos l'issue, normalement plus de problème.
