### ISSUE TITLE
[Proposal] Find a way to import Rutorrent settings inside the container

### ISSUE THREAD

**Issue by Djamy** [xataz/dockerfiles#22]
Hi,

I think it would be cool and useful to be able to import/mount our own Rutorrent settings folder inside the rtorrent-rutorrent container.

In that way, it will be possible to launch a new container with everything loaded and ready to use.
This mount should be available for both cases : with a Webroot and without.

I wanted to create a PR about this but I'm struggling with the command `mv /var/www/html/torrent` inside the [startup script](https://github.com/xataz/dockerfiles/blob/master/rtorrent-rutorrent/rootfs/usr/local/bin/startup)..

**Comment by xataz** [comment]
Hi Djamy,

Yes it's a good idea. 
I look that asap.

**Comment by Djamy** [comment]
Great, thanks !
