### ISSUE TITLE
rtorrent-rutorrent : Images on docker hub are not base on this Dockerfile

### ISSUE THREAD

**Issue by Djamy** [xataz/dockerfiles#24]
Hi,

When you use the image ` xataz/rtorrent-rutorrent:latest-filebot` or even when you try to run `docker build -t xataz/rtorrent-rutorrent:custom --build-arg WITH_FILEBOT=YES github.com/xataz/dockerfiles.git#master:rtorrent-rutorrent` the image seems to not be based on [this folder](https://github.com/xataz/dockerfiles/tree/master/rtorrent-rutorrent).

To reproduce, I built an image with the command above and went inside the container and made `cat /usr/local/bin/startup`

I got a different file from the one [here](https://github.com/xataz/dockerfiles/blob/master/rtorrent-rutorrent/rootfs/usr/local/bin/startup).

Probably a mismatch between this repo and your own private one ?

**Comment by xataz** [comment]
It's good !!!
