### ISSUE TITLE
rtorrent-rutorrent: HTTPS trackers timeout

### ISSUE THREAD

**Issue by ewan2395** [xataz/dockerfiles#30]
Torrents which use a HTTPS tracker will timeout; modifying the torrent to use HTTP results in a successful connection.

This behaviour has beeen reproduced over many different trackers using the latest docker image.

**Comment by Wonderfall** [comment]
I confirm that, I get the same with my own alpine-based image of rtorrent.

**Comment by Djamy** [comment]
This is probably in relation with the issue #25 ?

**Comment by ewan2395** [comment]
I rebuilt the image using apline 3.4 + openssl but the issue still persists.

http://pastebin.com/wYqk819m

**Comment by xataz** [comment]
Are you a public tracker name for I try fix it ?

**Comment by Wonderfall** [comment]
@xataz If you remember I invited you to IPT, you can enable SSL tracker in the settings.

**Comment by xataz** [comment]
Yes, I have same error.
I try rebuild with alpine:3.4 (official and self) with openssl and libressl, same error. But works with a old version of xataz/rtorrent-rutorrent.
I will try to use official package of libtorrent and rtorrent, if works or not.

**Comment by Wonderfall** [comment]
Yes something has changed as it used to work before, a package I don't know, there must be an explanation.

**Comment by xataz** [comment]
I try with official package of libtorrent and rtorrent, same problem.

**Comment by ewan2395** [comment]
I'm fairly certain the issue is linked to the newest version of curl

https://github.com/rakshasa/rtorrent/issues/535
https://github.com/rakshasa/rtorrent/issues/538

**Comment by xataz** [comment]
Same patch in this commit (3 days) : 
https://github.com/alpinelinux/aports/commit/262629094f233d25f4c19ed7a07f556f5763b58d

I build now rtorrent-rutorrent, you can retry in 1 hour.

**Comment by ewan2395** [comment]
I can confirm HTTPS is now working. 

Thanks.
