### ISSUE TITLE
[drone] No help topic for '${SERVER_OR_AGENT}'

### ISSUE THREAD

**Issue by Dryusdan** [xataz/dockerfiles#43]
La commande CMD du dockerfile de drone ne fonctionne pas lors de l’exécution de cette dernière. Cela fait cracher le container avec comme message :  "No help topic for '${SERVER_OR_AGENT}'"

Voici l docker run de ce dernier : 

`#!/bin/sh
docker run 
--name drone  
-e DRONE_GITLAB=true
-e DRONE_GITLAB_URL=giturl 
-e DRONE_GITLAB_CLIENT=id   
-e DRONE_GITLAB_SECRET=secret
-e SERVER_OR_AGENT=server
--network front --ip 172.20.1.20  
--restart always -d xataz/drone`

Si vous avez besoin d'autre information ;)

**Comment by xataz** [comment]
Je suis en train de refaire l'image

**Comment by xataz** [comment]
Pour finir, l'image officiel est carrément mieux, j'ai donc supprimé la mienne.
Je clos donc l'issue
