### ISSUE TITLE
rtorrent : scgi don't work

### ISSUE THREAD

**Issue by Hydrog3n** [xataz/dockerfiles#45]
Salut,
Après plusieurs tentative de trouver l'origine du problème j'ai un peu fini par comprendre. 

j'ai fait un netstat -pnl  le plus rapidement après le reboot et je vois qu'il y a un écoute mais si je relance juste après ça n'y est plus. 

J'ai lancé en root sur le container rtorrent et là ça fonctionne sans problème... Il y a un truc qui bloque mais j'ai pas réussi en activant de log et autre... 

J'ai chmod 777 mon dossier data et j'ai le même UID et GID partout. 

Du coup si vous avez des idées pour débugé afin d'avoir plus de chose je suis preneur !

**Comment by Dryusdan** [comment]
La dernière fois, et c'est le même problème, il a fallu ajouter TERM=xterm en variable d'environnement (je ne sais toujours pas pourquoi)

**Comment by Hydrog3n** [comment]
@Dryusdan Et bien merci beaucoup ! 

J'ai rajouter la variable dans mon docker-compose et ça fonctionne nickel 

ENGLISH : You need to add TERM=xterm in env my i add in docker-compose.yml this is magic :D

**Comment by xataz** [comment]
Solved
