### ISSUE TITLE
[nginx-reverse] Protocol unsupported

### ISSUE THREAD

**Issue by Hydrog3n** [xataz/dockerfiles#46]
Salut, j'ai installer nextcloud de @Wonderfall et quand je veux connecter le client nextcloud ça fonctionne pas nginx retourne l'erreur suivante : 

```
 2017/04/07 15:13:04 [crit] 279#279: *2541 SSL_do_handshake() failed (SSL: error:14076102:SSL routines:SSL23_GET_CLIENT_HELLO:unsupported protocol) while SSL handshaking, client: 80.215.171.167, server: 0.0.0.0:8443
```

Une piste ?

**Comment by Hydrog3n** [comment]
J'ai trouvé une informatio @xataz https://github.com/nextcloud/client_theming/issues/13

Je peux activé le TLSv1 ?

**Comment by xataz** [comment]
Salut, Tu es sous quel OS ? J'ai eu le problème sur macOS, sur linux et windows, y'avais aucun soucis.
Pour le TLSv1, j'ai pas prévu ceci, il faudrait modifier l'image.

**Comment by Hydrog3n** [comment]
@xataz Je suis sous mac OS x j'ai oublié de précisé.

**Comment by xataz** [comment]
C'était un peu long, mais je suis dessus, avec la possibilité de modifier les ciphers aussi ^^

**Comment by xataz** [comment]
Voilà c'est ajouté ^^
