### ISSUE TITLE
[rtorrent-rutorrent] Use {plex} for FileBot renaming

### ISSUE THREAD

**Issue by welcoMattic** [xataz/dockerfiles#48]
We can use this trick to rename files : 
https://www.filebot.net/forums/viewtopic.php?f=5&t=4116

What do you think?

**Comment by xataz** [comment]
I can add environment variables for add custom Naming Schemes.

I'm trying to look at that tonight.

**Comment by xataz** [comment]
it's ok.

I add 5 environments variables for configure filebot.

See README.md

I close this issue
