### ISSUE TITLE
[rtorrent-rutorrent] 100% CPU

### ISSUE THREAD

**Issue by PixiBixi** [xataz/dockerfiles#49]
Salut xataz,

Tu dois être au courant du bug, mais rtorrent utilise 100% de CPU :/

Si tu pouvais regarder ça :)

BXT

**Comment by PixiBixi** [comment]
Linux nonoss 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 GNU/Linux

Containers: 19
 Running: 12
 Paused: 0
 Stopped: 7
Images: 23
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-8:2-263096-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.03GB
 Data Space Total: 107.4GB
 Data Space Available: 9.477GB
 Metadata Space Used: 12.08MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.135GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.14.32-xxxx-grs-ipv6-64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.829GiB
Name: nonoss
ID: MWUZ:FXEE:SNSI:YQID:DZK5:E6SW:RIHB:6O4O:6YUI:3HQC:763O:TIYX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

Intéréssant ces warnings, surtout celui sur le kernel memory limit

**Comment by Wonderfall** [comment]
Je fais le lien avec : https://github.com/Wonderfall/dockerfiles/issues/156

**Comment by PixiBixi** [comment]
Je vois 3 process rtorrent sur un serveur a 2 threads déjà, je trouve ça très bizarre

https://i.imgur.com/bxu0hZs.png

Si je strace les 3 process, beaucoup (trop ?) de epoll_pwait sur le process à 100%, alors que les autres ont un epoll_wait toutes les secondes, je pense que ça vient de là

Après comment le fix ? :D

**Comment by arckosfr** [comment]
Perso
```
Containers: 17
 Running: 17
 Paused: 0
 Stopped: 0
Images: 18
Server Version: 17.04.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.9.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.63GiB
Name: sd-40499
ID: PIVI:MKJG:WDT5:CZ5T:GTOM:AV5P:WLMH:GYQN:HEWF:KPKR:M5WQ:76Y4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
pas de soucis de CPU sur les deux rtorrent :/

**Comment by PixiBixi** [comment]
Go faire un docker inspect rutorrent (Ou le nom de ton container)

Doit y avoir un truc logique dans tout ça

**Comment by xataz** [comment]
Et y'a également la différence du driver de stockage, arckosfr comme moi utilisons btrfs, wonderfall utilise overlay, et toi aufs.

**Comment by PixiBixi** [comment]
Ouep, mais ça, ça avait déjà été dit, donc ça doit pas venir de là

**Comment by Wonderfall** [comment]
Je poste intégralement mon `docker info` si besoin.

```
Containers: 37
 Running: 37
 Paused: 0
 Stopped: 0
Images: 123
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.1
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.16GiB
Name: drogon
ID: TGPJ:KNGK:XV7N:LHP3:BXZG:AHLJ:QOR3:AL6F:ZHME:LHFZ:YBRP:MT4M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by xataz** [comment]
Voici le mien également : 
```shell
Containers: 27
 Running: 26
 Paused: 0
 Stopped: 1
Images: 586
Server Version: 17.05.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32GiB
Name: sldock01
ID: TZD5:QZCK:EIRU:5USK:NKBY:K537:AF5U:HLE2:XKC5:TNF6:J4V4:T3FD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xataz
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by Wonderfall** [comment]
Bon il y a pas 10 000 différences comparables.
OS ? non. Kernel ? non. CPU/RAM ? non. Version du Docker Engine ? non. Autres paramètres (Apparmor, Live Restore, et compagnie) ? non. Fs ? Pour l'instant aucun problème avec Btrfs.

Du coup je suis tenté pour tester sur btrfs et faire un retour. Il suffit que je refasse tous mes conteneurs une fois que Docker utilise par exemple /docker un volume formaté avec btrfs ?

**Comment by Wonderfall** [comment]
Juste pour être sûr, @arckosfr et @xataz, vous utilisez bien la dernière image dispo ? Pareil pour @PixiBixi ? Bon vous utilisez tous les 3 la même image, mais j'ai le même souci avec la mienne et d'autres utilisations de la mienne aussi se sont plaints, que ce soit quand on était sur edge ou sur 3.5.

**Comment by Hydrog3n** [comment]
Yop je poste le miens aussi car j'ai le soucis aussi depuis que j'ai rajouté l'env TERM=xterm 
```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 17.04.0-ce
Storage Driver: devicemapper
 Pool Name: docker-9:2-1953-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 13.25GB
 Data Space Total: 107.4GB
 Data Space Available: 5.078GB
 Metadata Space Used: 10.32MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.137GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.14.32-xxxx-grs-ipv6-64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 31.41GiB
Name: riddler
ID: BQLL:BE2H:TT5K:H7WS:M4ZA:X737:FX53:5OIW:VZ3Z:KJ5Q:IUJU:EVDS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by arckosfr** [comment]
@Wonderfall Oui derniere version pour ma part

**Comment by Hydrog3n** [comment]
@Wonderfall En vrais je pense pas grand chose mais quand le scgi ne tourné j'avais pas ça. J'écris ce que j'ai constaté. C'est pas forcément juste.

**Comment by xataz** [comment]
Dernière version pour moi aussi, j'ai pas la variable TERM.

**Comment by Wonderfall** [comment]
Du coup @xataz ou @arckosfr quelqu'un peut tester la variable TERM=xterm ? Perso elle est par défaut dans mon image, je sais plus pour quelle raison mais c'était nécessaire pour afficher rtorrent en CLI je crois.

**Comment by xataz** [comment]
Je pourrais tester ce soir, mais pas avant, perso je démarre le conteneur avec tty: yes

**Comment by Wonderfall** [comment]
J'ai rien dit j'ai confondu d'image, la mienne ne set pas TERM=xterm par défaut.
Donc ça vient pas de là je pense...

**Comment by xataz** [comment]
Si sur la tienne elle set ça dans le run de rtorrent

**Comment by Wonderfall** [comment]
Ah j'ai carrément oublié, possible...

**Comment by Wonderfall** [comment]
Donc j'ai rajouté le `tty: true`, redémarré et j'ai pas le bug mais je crois qu'il arrive en attendant un peu.

**Comment by Wonderfall** [comment]
Peut-être que ça arrive quand rtorrrent bouffe toute la RAM disponible ? Comme il le fait j'ai mis une limite à 10G parce que sinon c'était n'importe quoi (rtorrent en vert)

![](https://img.targaryen.house/B5V5pAvL/VDHbrcfY.jpg)

**Comment by PixiBixi** [comment]
Plop

Pareil pour moi, rTorrent ne démarre pas sans TERM=xterm. Sinon, on m'a prêté un Kimsufi aujourd'hui, je vais tester avec brtfs ;)

**Comment by Wonderfall** [comment]
Pour ma part j'ai attendu que rtorrent utilise la RAM au maximum et le bug n'est pas réapparu avec `tty: true`. Je vous tiens au courant.

**Comment by PixiBixi** [comment]
tty: true avec TERM=xterm, ou sans ?

**Comment by Wonderfall** [comment]
J'ai laissé le TERM=xterm perso, j'ai juste recréé le conteneur avec `tty: true` dans le docker-compose. Toujours pas de bug.

**Comment by PixiBixi** [comment]
Intéréssant, je vais essayer de ce pas

**Comment by Hydrog3n** [comment]
Donc j'ai fait un test en enlevant TERM=xterm et en rajoutant tty: true. J'ai pas de process à 100% et le sgci fonctionne. 
```
  rutorrent:
    image: xataz/rtorrent-rutorrent:latest
#-filebot
    container_name: rutorrent
    restart: always
    volumes:
      - /docker/rutorrent/config:/config
      - /home/riddler:/data
    ports:
      - "45000:45000"
    environment:
#      - TERM=xterm
      - GID=1001
      - UID=1001
    networks:
      - proxy
    tty: true
```

**Comment by PixiBixi** [comment]
Perso j'ai gardé la variable TERM moi

**Comment by xataz** [comment]
Je suis en train de testé une bidouille avec s6-fghack + screen. J'espère qu'avec ça, plus besoin de TERM et tty.

Sinon, une idée de pourquoi TERM agit comme ceci ?

**Comment by xataz** [comment]
Ma solution avec s6-fghack + screen semble fonctionnel, je continue les tests pour voir. De plus avec ceci, le stdin et stdout ne sont pas polué par l'ui de rtorrent.

**Comment by Hydrog3n** [comment]
@xataz du coup tu as gardé TERM=xterm ?

**Comment by PixiBixi** [comment]
Quelle est ta solution @xataz ?

Le term et tty: ne me gène pas perso ? ^^

**Comment by xataz** [comment]
Ba maintenant y'a plus besoin de rien, j'ai mis hier sur mon serveur la nouvelle version de rtorrent-rutorrent, et j'ai pas eu de soucis.

**Comment by PixiBixi** [comment]
Oké, j'avais pas vu passer le commit :P

**Comment by Wonderfall** [comment]
Du coup je vais piquer le commit pour mon image. 😇
Une idée du problème que c'était au final ?

**Comment by xataz** [comment]
Erreur de ma part, j'ai un export TERM=xterm dans le s6.d/torrent/run de rtorrent (Je sais pas quand je l'ai ajouté en fait, il a du rester de mes tests ^^)

En fait ce que je soupçonne, c'est que le fait de lancer rtorrent sans screen, surcharge stdout ou un truc comme ça.

**Comment by Hydrog3n** [comment]
@xataz Ah je me demandé pourquoi il était là celui là ! D'ou le tu as gardé TERM=xterm :)

**Comment by xataz** [comment]
J'ai bien le xterm dans le script de lancement de rtorrent, mais par contre, j'ai plus ni TERM ni tty dans mon docker-compose.yml
