### ISSUE TITLE
[Lutim]Can't load application from file

### ISSUE THREAD

**Issue by Dryusdan** [xataz/dockerfiles#54]
The lutim image can't start properly and restart everytime with this log :   
```
Can't load application from file "/usr/lutim/script/lutim": Can't locate object method "rel_dir" via package "Mojo::Home" at /usr/lutim/script/../lib/Mounter.pm line 32.
Compilation failed in require at (eval 82) line 1.
```

:)

**Comment by arckosfr** [comment]
linked to : https://framagit.org/luc/lutim/issues/45
wait for dev to accept PR : https://framagit.org/luc/lutim/merge_requests/10

**Comment by arckosfr** [comment]
The PR is merged, a container need a build 👍

**Comment by xataz** [comment]
J'ai relancé un build, mais j'ai une erreur avec le module Image::Magick, je regarde ceci ce soir.

**Comment by xataz** [comment]
Build with new commit OK

Close this issue
