### ISSUE TITLE
Mediainfo with filebot

### ISSUE THREAD

**Issue by rix1337** [xataz/dockerfiles#6]
https://github.com/rix1337/docker-verarbeitung/blob/master/Dockerfile

I am pulling my hair out trying to get filebot to find mediainfo.

Any idea how to integrate mediainfo with filebot on alpine?

**Comment by Tap3** [comment]
Same here, actually the only way is to use an OS based on Debian

**Comment by xataz** [comment]
Hi,

For that : 
- Compile libmediainfo, mediainfo, and libzen
- Install (manually) fpcalc (chromaprint)
- Link libmediainfo and libzen on filebot folder

I close this issue
