### ISSUE TITLE
[LUFI] Rien ne s'upload

### ISSUE THREAD

**Issue by Rathorian** [xataz/dockerfiles#62]
Salut,

Comme expliqué dans le titre, rien ne s'upload.
Tu peux essayer sur https://up.rathorian.fr

Même une image de 14Ko ne s'upload pas et j'avoue ne pas trouver la source du problème....

Mon docker-compose : https://paste.mondedie.fr/?855551fe7c9928d6#5/Dn0KiBOM49B57L38Hmr96E6Fkrr4xKqS/1hzA6dXU=

Quand je fais un "docker logs lufi" j'obtiens : 
`Unknown option: listen`
`Server available at http://0.0.0.0:8081`
Le **Unknown option: listen** me plaît pas trop !

Dans le conteneur, les logs de l'appli dans production.log, rien d'anormal : 
`[Sun Oct  1 15:15:26 2017] [info] Listening at "http://0.0.0.0:8081"`
`[Sun Oct  1 15:15:26 2017] [info] Manager 13 started`
`[Sun Oct  1 15:15:26 2017] [info] Creating process id file "/usr/lufi/script/hypnotoad.pid"`

Si tu as une idée
Merci

**Comment by Hydrog3n** [comment]
Salut, tu as une erreur avec le websocket sur la console. 

Regarde ta configuration serveur pour le websocket si non rien ne s'uploadera.

**Comment by Rathorian** [comment]
Salut,

Pour être tout à fait honnête, j'ai beau regarder sur internet plusieurs liens, je comprends pas trop la définition du Websocket...

Du coup, pour corriger le problème, je trouve pas !

**Comment by Rathorian** [comment]
Je viens de regarder un peu plus attentivement ton message @Hydrog3n et effectivement, j'ai enfin trouvé de quoi tu me parlais : https://images.mondedie.fr/gallery#WZmxL0j0/hmMMVlC9.png

Le problème c'est que je vois pas vraiment ce que je peux faire pour le coup, sur internet il y a très peu d'information à ce sujet et qui ne sont pas forcément viable pour moi.

Je ne fais qu'utiliser un conteneur et je pense l'utiliser comme c'est décrit dans la doc de @xataz

**Comment by Hydrog3n** [comment]
Je viens de voir que sur Mondedie nous n'avons pas le wss... Il faudrait peut être revoir la config du serveur web dans le container. 

J'ai pas du tout le temps pour regarder ça plus en profondeur.

**Comment by Hydrog3n** [comment]
Bon ça m'a chatouillé l'esprit j'ai lu sur la doc pour nginx qu'il y a un remarque pour le websocket : https://framagit.org/luc/lufi/wikis/installation#putting-lufi-behind-nginx

Je te conseil de regarder les paramétres et de faire coller ta conf nginx avec celle-ci.

**Comment by Hydrog3n** [comment]
@Rathorian C'était quoi ?
